const CARDS_PART3 = [
  // ===== MONSTER CARDS (m81-m100) =====
  { id: 'm81', name: "Dark Ruler Ha Des", atk: 2450, def: 1300, type: 'monster', level: 6, attribute: 'dark', species: 'fiend', effect: null, description: '(This card is always treated as an "Archfiend" card.)\nIf a Level 8 or higher monster under your control was sent to the Graveyard this turn: Special Summon 1 "Berserk Dragon" from your hand or Deck.' },
  { id: 'm82', name: "Mausoleum of the Emperor", type: 'spell', category: 'field', effect: 'field_spell', description: 'During any Main Phase: The turn player can pay 1000 LP x the number of monsters normally needed for the Tribute Summon of a monster (max. 2000); that player Normal Summons/Sets that monster without Tributing. (This is their one Normal Summon/Set for that turn. This is not a Tribute Summon.)' },
  { id: 'm83', name: "Nights End", atk: 1000, def: 600, type: 'monster', level: 3, attribute: 'dark', species: 'spellcaster', effect: null, description: '2 Level 4 "Noble Knight" monsters\nWhen this card is Xyz Summoned: You can target up to 3 "Noble Arms" Equip Spell Cards with different names in your Graveyard; equip those targets to this card. Once per turn: You can detach 1 Xyz Material from this card; destroy any number of Spell/Trap Cards on the field, up to the number of "Noble Arms" Equip Spell Cards you control.' },
  { id: 'm84', name: "Soul Demolition", atk: 1300, def: 1000, type: 'monster', level: 4, attribute: 'dark', species: 'spellcaster', effect: null, description: 'You can only Special Summon "Abominable Unchained Soul(s)" once per turn. If a card(s) you control is destroyed by battle or card effect: You can Special Summon this card from your hand. If this card is Special Summoned: You can discard 1 card; destroy 1 card on the field. Once per turn, during the End Phase, if this card is in the GY because it was destroyed on the field and sent there this turn: You can Special Summon this card, but place it on the bottom of the Deck when it leaves the field.'s monster by battle, you can excavate the top 3 cards of your Deck and return them to the deck in any order." },
  { id: 'm85', name: "Dark Grepher", atk: 1850, def: 800, type: 'monster', level: 4, attribute: 'dark', species: 'warrior', effect: null, description: '(This card is always treated as an "Archfiend" card.)\nIf a Level 8 or higher monster under your control was sent to the Graveyard this turn: Special Summon 1 "Berserk Dragon" from your hand or Deck.' },
  { id: 'm86', name: "Armageddon Knight", atk: 1400, def: 1200, type: 'monster', level: 4, attribute: 'dark', species: 'warrior', effect: null, description: '2 Level 5 monsters\nOnce per turn: You can detach 1 Xyz Material from this card to target 1 face-up card your opponent controls; destroy it.' },
  { id: 'm87', name: "Shadow Slayer", atk: 1600, def: 1200, type: 'monster', level: 5, attribute: 'dark', species: 'warrior', effect: null, description: '2+ monsters, including a Fiend monster\nDuring the Main Phase (Quick Effect): You can discard 1 card, then activate 1 of these effects;\n● Destroy 1 card on the field.\n● Banish this card (until the End Phase), and if you do, Special Summon 1 LIGHT or DARK monster from your GY.\nDuring your Standby Phase: You can draw cards equal to the number of different Monster Types in your GY, then place cards from your hand on the bottom of the Deck in any order, equal to the number of cards you drew. You can only use each effect of "A Bao A Qu, the Lightless Shadow" once per turn.' },
  { id: 'm88', name: "Morphing Jar", atk: 700, def: 600, type: 'monster', level: 2, attribute: 'earth', species: 'rock', effect: 'flip_morphing_jar', description: 'FLIP: Both players discard as many cards as possible from their hands, then each player draws 5 cards.' },
  { id: 'm89', name: "Sangan", atk: 1000, def: 600, type: 'monster', level: 3, attribute: 'dark', species: 'fiend', effect: 'search_1500_atk', description: 'Originally a pterodactyl, he was viciously attacked by a dragon. Using the newest technologies, his keeper saved him from near-fatal wounds and brought him back as a powerful Cyborg.' },
  { id: 'm90', name: "Kuriboh", atk: 300, def: 200, type: 'monster', level: 1, attribute: 'dark', species: 'fiend', effect: 'prevent_battle_damage', description: 'Once per turn, you can either: Target 1 LIGHT Machine monster you control; equip this card to that target, OR: Unequip this card and Special Summon it. A monster equipped with this card is unaffected by your opponent\'s monster effects (except its own), also if the equipped monster would be destroyed by battle or card effect, destroy this card instead. If this card is sent from the field to the GY: You can add 1 other Union monster from your GY to your hand.'s turn, at damage calculation: You can discard this card; you take no battle damage from that battle (this is a Quick Effect)." },
  { id: 'm91', name: "Chrysanthemum", atk: 1000, def: 1000, type: 'monster', level: 3, attribute: 'earth', species: 'plant', effect: 'flip_draw_2', description: 'You can Tribute this card from your hand or face-up field, then target up to 2 Plant monsters you control; reduce their Level(s) by 2 until the end of this turn. During the End Phase, if this card is in the GY because it was Tributed and sent there this turn: You can Special Summon this card, but banish it when it leaves the field. You can only use each effect of "Cyclamen the Rikka Fairy" once per turn.' },
  { id: 'm92', name: "D.D. Crow", atk: 1000, def: 800, type: 'monster', level: 3, attribute: 'dark', species: 'winged beast', effect: null, description: 'After damage calculation, when this card is destroyed by battle with an opponent\'s monster: Banish that monster, also banish this card.'s Main Phase: You can banish 1 card from your opponent's hand. This effect cannot be used the turn this card is Summoned." },
  { id: 'm93', name: "Kahkki", atk: 800, def: 700, type: 'monster', level: 2, attribute: 'water', species: 'fish', effect: null, description: 'If this card is discarded to the Graveyard by a card effect: Target 1 monster on the field; destroy that target.' },
  { id: 'm94', name: "Giant Rat", atk: 1200, def: 800, type: 'monster', level: 4, attribute: 'earth', species: 'beast', effect: null, description: 'Return 1 Level 5 or higher Dragon-Type monster you control to the hand, and if you do, destroy all Spell and Trap Cards on the field.' },
  { id: 'm95', name: "The Emperor's Priestess", atk: 1400, def: 1200, type: 'monster', level: 5, attribute: 'light', species: 'spellcaster', effect: null, description: '2+ monsters, including a Fiend monster\nDuring the Main Phase (Quick Effect): You can discard 1 card, then activate 1 of these effects;\n● Destroy 1 card on the field.\n● Banish this card (until the End Phase), and if you do, Special Summon 1 LIGHT or DARK monster from your GY.\nDuring your Standby Phase: You can draw cards equal to the number of different Monster Types in your GY, then place cards from your hand on the bottom of the Deck in any order, equal to the number of cards you drew. You can only use each effect of "A Bao A Qu, the Lightless Shadow" once per turn.'s name is treated as 'Breaker the Magical Warrior' on the field." },
  { id: 'm96', name: "Spirit of the Potter", atk: 900, def: 1100, type: 'monster', level: 4, attribute: 'earth', species: 'rock', effect: null, description: '(This card is always treated as a "Mermail" card.)\nYou can Tribute this card from your hand and 1 "Atlantean" or "Mermail" monster from your hand or field; take 1 Level 7 Fish, Sea Serpent, or Aqua monster from your Deck and either add it to your hand or Special Summon it, also you cannot Special Summon from the Extra Deck for the rest of this turn, except WATER monsters. During your opponent\'s turn (Quick Effect): You can banish this card from your GY and discard 1 card to the GY; draw 1 card. You can only use each effect of "Abyssrhine, the Atlantean Spirit" once per turn.' },
  { id: 'm97', name: "Guardian of the Throne Room", atk: 1500, def: 1700, type: 'monster', level: 6, attribute: 'light', species: 'spellcaster', effect: null, description: 'Activate this Skill during your Main Phase. Shuffle your entire hand into the Deck, then add 1 Level 11 monster from your Deck to your hand, and if you do, you can Special Summon up to 2 Level 7 monsters with different Attributes from your Deck and/or GY, but their ATK/DEF become 0, also their effects are negated. While you control "Gate Guardian", it gains the following effect.\n● Once while face-up on the field, when this card is targeted for an attack: You can change the attacking monster\'s ATK to 0, until the end of the Damage Step.' },
  { id: 'm98', name: "Freed the Brave Wanderer", atk: 1600, def: 900, type: 'monster', level: 4, attribute: 'light', species: 'warrior', effect: null, description: 'Cannot be Special Summoned. Negate any Spell effects that target a face-up DARK monster(s) you control, and if you do, destroy that Spell Card. During your Draw Phase, instead of conducting your normal draw: You can add 1 Level 4 DARK monster from your Deck to your hand. This card must be face-up on the field to activate and to resolve this effect.'The Trieagle', you can Normal Summon this card without Tributing." },
  { id: 'm99', name: "Marauding Captain", atk: 1200, def: 800, type: 'monster', level: 3, attribute: 'light', species: 'warrior', effect: null, description: 'When this card declares an attack, your opponent cannot activate cards or effects. If this card attacks, it is changed to Defense Position at the end of the Battle Phase, and its battle position cannot be changed until the End Phase of your next turn.' },
  { id: 'm100', name: "D.D. Scout Plane", atk: 1400, def: 800, type: 'monster', level: 4, attribute: 'dark', species: 'machine', effect: null, description: 'After damage calculation, when this card is destroyed by battle with an opponent\'s monster: Banish that monster, also banish this card.' },

  // ===== EXODIA WIN CONDITION CARDS (m101-m105) =====
  { id: 'm101', name: "Exodia the Forbidden One", atk: 1000, def: 1000, type: 'monster', level: 3, attribute: 'dark', species: 'spellcaster', effect: 'exodia_piece', exodiaPiece: 'head', description: 'If you have "Right Leg of the Forbidden One", "Left Leg of the Forbidden One", "Right Arm of the Forbidden One" and "Left Arm of the Forbidden One" in addition to this card in your hand, you win the Duel.' },
  { id: 'm102', name: "Right Arm of the Forbidden One", atk: 200, def: 300, type: 'monster', level: 1, attribute: 'dark', species: 'spellcaster', effect: 'exodia_piece', exodiaPiece: 'right_arm', description: 'A forbidden right arm sealed by magic. Whosoever breaks this seal will know infinite power.' },
  { id: 'm103', name: "Left Arm of the Forbidden One", atk: 200, def: 300, type: 'monster', level: 1, attribute: 'dark', species: 'spellcaster', effect: 'exodia_piece', exodiaPiece: 'left_arm', description: 'A forbidden left arm sealed by magic. Whosoever breaks this seal will know infinite power.' },
  { id: 'm104', name: "Right Leg of the Forbidden One", atk: 200, def: 300, type: 'monster', level: 1, attribute: 'dark', species: 'spellcaster', effect: 'exodia_piece', exodiaPiece: 'right_leg', description: 'A forbidden right leg sealed by magic. Whosoever breaks this seal will know infinite power.' },
  { id: 'm105', name: "Left Leg of the Forbidden One", atk: 200, def: 300, type: 'monster', level: 1, attribute: 'dark', species: 'spellcaster', effect: 'exodia_piece', exodiaPiece: 'left_leg', description: 'A forbidden left leg sealed by magic. Whosoever breaks this seal will know infinite power.' },

  // ===== SPELL CARDS (s1-s15) =====
  { id: 's1', name: "Dark Hole", type: 'spell', category: 'normal', effect: 'destroy_all_monsters', description: '(This card is always treated as an "Archfiend" card.)\nIf a Level 8 or higher monster under your control was sent to the Graveyard this turn: Special Summon 1 "Berserk Dragon" from your hand or Deck.' },
  { id: 's2', name: "Monster Reborn", type: 'spell', category: 'normal', effect: 'special_summon_grave', description: 'If your opponent controls a monster and you control no monsters: Special Summon from your hand, 1 monster with an original Level of 10 or lower that cannot be Normal Summoned/Set, ignoring its Summoning conditions. It is unaffected by the effects of your cards, except for its own effects and this card\'s, also shuffle it into the Deck during your opponent\'s next End Phase. For the rest of this turn, you cannot Normal Summon/Set or Special Summon monsters, and your opponent takes no damage.' },
  { id: 's3', name: "Swords of Revealing Light", type: 'spell', category: 'normal', effect: 'flip_monsters_up', description: 'Your opponent takes any battle damage you would have taken from battles involving this card instead.'s activation." },
  { id: 's4', name: "Change of Heart", type: 'spell', category: 'quick-play', effect: 'take_control_opponent_monster', description: 'You can banish this card from your Graveyard, then target 1 monster on the field; change its battle position.'s monster; take control of it until the End Phase." },
  { id: 's5', name: "The Hall of Dragon", type: 'spell', category: 'normal', effect: 'damage_1000', description: '2+ monsters, including a Fiend monster\nDuring the Main Phase (Quick Effect): You can discard 1 card, then activate 1 of these effects;\n● Destroy 1 card on the field.\n● Banish this card (until the End Phase), and if you do, Special Summon 1 LIGHT or DARK monster from your GY.\nDuring your Standby Phase: You can draw cards equal to the number of different Monster Types in your GY, then place cards from your hand on the bottom of the Deck in any order, equal to the number of cards you drew. You can only use each effect of "A Bao A Qu, the Lightless Shadow" once per turn.' },
  { id: 's6', name: "Dark Magic Veil", type: 'spell', category: 'normal', effect: 'destroy_opponent_backrow', description: '(This card is always treated as an "Archfiend" card.)\nIf a Level 8 or higher monster under your control was sent to the Graveyard this turn: Special Summon 1 "Berserk Dragon" from your hand or Deck.' },
  { id: 's7', name: "Mage Power", type: 'spell', category: 'equip', effect: 'boost_by_spells', description: '2 Level 5 monsters\nOnce per turn: You can detach 1 Xyz Material from this card to target 1 face-up card your opponent controls; destroy it.' },
  { id: 's8', name: "Premature Burial", type: 'spell', category: 'continuous', effect: 'special_summon_self_gy', description: 'Activate this card by paying 800 LP, then target 1 monster in your Graveyard; Special Summon that target in Attack Position and equip it with this card. When this card is destroyed, destroy the equipped monster.' },
  { id: 's9', name: "Reload", type: 'spell', category: 'normal', effect: 'reload_hand', description: 'This card\'s name becomes "Tri-Blaze Accelerator" while in the Spell & Trap Zone. During either player\'s Main Phase: You can send 1 "Volcanic" card from your hand to the Graveyard, and if you do, draw 1 card. You can only use this effect of "Blaze Accelerator Reload" once per turn. During either player\'s Main Phase: You can banish this card from your Graveyard; send 1 "Volcanic" card from your Deck to the Graveyard.' },
  { id: 's10', name: "Snatch Strike", type: 'spell', category: 'quick-play', effect: 'steal_opponent_card', description: 'When you Tribute Summon a monster: You can Special Summon this card from your hand, and if you do, the Type, Attribute, and Level of this card become the same as that face-up Tribute Summoned monster.'s Main Phase: Target 1 face-up monster your opponent controls; take control of it until the End Phase." },
  { id: 's11', name: "Mind Control", type: 'spell', category: 'normal', effect: 'take_control_until_end', description: 'A high-performance unit developed to enhance the Artificial Intelligence program of the Allies of Justice. Loaded with elements collected from a meteor found in the Worm Nebula, it allows for highly tuned processing. But its full capacity is not yet determined.' },
  { id: 's12', name: "Dark Magic Curtain", type: 'spell', category: 'ritual', effect: 'ritual_summon', description: '(This card is always treated as an "Archfiend" card.)\nIf a Level 8 or higher monster under your control was sent to the Graveyard this turn: Special Summon 1 "Berserk Dragon" from your hand or Deck.'Dark Magician'. You must also send monsters from your hand or field to the GY whose total Levels equal 7." },
  { id: 's13', name: "Gold Sarcophagus", type: 'spell', category: 'normal', effect: 'banish_top_deck', description: '[ Pendulum Effect ] \n"Amazoness" monsters you control gain ATK equal to their own Level x 100. When an attack is declared involving your "Amazoness" monster: You can target 1 Spell/Trap on the field; destroy it. You can only use this effect of "Amazoness Golden Whip Master" once per turn.\n\n[ Monster Effect ] \nIf this card in the Monster Zone is destroyed by battle or card effect: You can place this card in your Pendulum Zone. If an "Amazoness" monster(s) is Special Summoned to your field, while this card is in your GY (except during the Damage Step): You can place this card in your Pendulum Zone. You can only use each effect of "Amazoness Golden Whip Master" once per turn.' },
  { id: 's14', name: "Mesmeric Control", type: 'spell', category: 'normal', effect: 'drain_opponent_stat', description: 'During your opponent\'s next turn after you activate this card, your opponent cannot change the battle positions of monsters, except with a card effect.' },
  { id: 's15', name: "The Necklace of Fate", type: 'spell', category: 'continuous', effect: 'prevent_death_damage', description: '2+ monsters, including a Fiend monster\nDuring the Main Phase (Quick Effect): You can discard 1 card, then activate 1 of these effects;\n● Destroy 1 card on the field.\n● Banish this card (until the End Phase), and if you do, Special Summon 1 LIGHT or DARK monster from your GY.\nDuring your Standby Phase: You can draw cards equal to the number of different Monster Types in your GY, then place cards from your hand on the bottom of the Deck in any order, equal to the number of cards you drew. You can only use each effect of "A Bao A Qu, the Lightless Shadow" once per turn.' }
];
export default CARDS_PART3;