const CARDS_PART4 = [
  // ===== SPELL CARDS =====
  { id: 's16', name: 'Goblin\'s Secret Remedy', type: 'spell', category: 'normal', effect: 'heal_500', description: 'Increase your Life Points by 600 points.' },
  { id: 's17', name: 'Hinotama', type: 'spell', category: 'normal', effect: 'damage_800', description: 'Inflict 500 damage to your opponent.' },
  { id: 's18', name: 'Final Flame', type: 'spell', category: 'normal', effect: 'damage_800', description: 'Inflict 600 points of damage to your opponent\'s Life Points.' },
  { id: 's19', name: 'Sparks', type: 'spell', category: 'normal', effect: 'damage_800', description: 'Inflict 200 points of damage to your opponent\'s Life Points.' },
  { id: 's20', name: 'Sword of Dark Destruction', type: 'spell', category: 'equip', effect: 'atk_boost', description: 'Equip only to a DARK monster. It gains 400 ATK and loses 200 DEF.' },
  { id: 's21', name: 'Book of Secret Arts', type: 'spell', category: 'equip', effect: 'atk_boost', description: 'A Spellcaster-Type monster equipped with this card increases its ATK and DEF by 300 points.' },
  { id: 's22', name: 'Dark Energy', type: 'spell', category: 'equip', effect: 'atk_boost', description: 'Increase the ATK and DEF of a Fiend-Type monster equipped with this card by 300 points.' },
  { id: 's23', name: 'Dragon Treasure', type: 'spell', category: 'equip', effect: 'atk_boost', description: 'A Dragon-Type monster equipped with this card increases its ATK and DEF by 300 points.' },
  { id: 's24', name: 'Electro-Whip', type: 'spell', category: 'equip', effect: 'atk_boost', description: 'Increase the ATK and DEF of a Thunder-Type monster equipped with this card by 300 points.' },
  { id: 's25', name: 'Follow Wind', type: 'spell', category: 'equip', effect: 'atk_boost', description: 'Increase the ATK and DEF of a Winged Beast-Type monster equipped with this card by 300 points.' },
  { id: 's26', name: 'Laser Cannon Armor', type: 'spell', category: 'equip', effect: 'atk_boost', description: 'Equip only to an Insect monster. It gains 300 ATK/DEF.' },
  { id: 's27', name: 'Legendary Sword', type: 'spell', category: 'equip', effect: 'atk_boost', description: 'Equip only to a Warrior monster. It gains 300 ATK/DEF.' },
  { id: 's28', name: 'Machine Conversion Factory', type: 'spell', category: 'equip', effect: 'atk_boost', description: 'Equip only to a Machine monster. It gains 300 ATK/DEF.' },
  { id: 's29', name: 'Mystical Moon', type: 'spell', category: 'equip', effect: 'atk_boost', description: 'Equip only to a Beast-Warrior-Type monster. It gains 300 ATK and DEF.' },
  { id: 's30', name: 'Power of Kaishin', type: 'spell', category: 'equip', effect: 'atk_boost', description: 'Equip only to an Aqua monster. It gains 300 ATK/DEF.' },
  { id: 's31', name: 'Raise Body Heat', type: 'spell', category: 'equip', effect: 'atk_boost', description: 'Equip only to a Dinosaur monster. It gains 300 ATK/DEF.' },
  { id: 's32', name: 'Silver Bow and Arrow', type: 'spell', category: 'equip', effect: 'atk_boost', description: 'A Fairy-Type monster equipped with this card increases its ATK and DEF by 300 points.' },
  { id: 's33', name: 'Vile Germs', type: 'spell', category: 'equip', effect: 'atk_boost', description: 'A Plant-Type monster equipped with this card increases its ATK and DEF by 300 points.' },
  { id: 's34', name: 'Violet Crystal', type: 'spell', category: 'equip', effect: 'atk_boost', description: '(This card is not treated as a "Crystal" card.)\nEquip only to a Zombie monster. It gains 300 ATK/DEF.' },
  { id: 's35', name: 'Beast Fangs', type: 'spell', category: 'equip', effect: 'atk_boost', description: 'A Beast-Type monster equipped with this card increases its ATK and DEF by 300 points.' },
  { id: 's36', name: 'Forest', type: 'spell', category: 'field', effect: 'field_spell', description: 'All Insect, Beast, Plant, and Beast-Warrior monsters on the field gain 200 ATK/DEF.' },
  { id: 's37', name: 'Mountain', type: 'spell', category: 'field', effect: 'field_spell', description: 'All Dragon, Winged Beast, and Thunder monsters on the field gain 200 ATK/DEF.' },
  { id: 's38', name: 'Sogen', type: 'spell', category: 'field', effect: 'field_spell', description: 'All Warrior and Beast-Warrior monsters on the field gain 200 ATK/DEF.' },
  { id: 's39', name: 'Umi', type: 'spell', category: 'field', effect: 'field_spell', description: 'All Fish, Sea Serpent, Thunder, and Aqua monsters on the field gain 200 ATK/DEF, also all Machine and Pyro monsters on the field lose 200 ATK/DEF.' },
  { id: 's40', name: 'Wasteland', type: 'spell', category: 'field', effect: 'field_spell', description: 'All Dinosaur, Zombie, and Rock monsters on the field gain 200 ATK/DEF.' },
  { id: 's41', name: 'Yami', type: 'spell', category: 'field', effect: 'field_spell', description: 'All Fiend and Spellcaster monsters on the field gain 200 ATK/DEF, also all Fairy monsters on the field lose 200 ATK/DEF.' },
  // ===== TRAP CARDS =====
  { id: 't1', name: 'Trap Hole', type: 'trap', effect: 'destroy_1000atk_monster', description: 'When your opponent Normal or Flip Summons 1 monster with 1000 or more ATK: Target that monster; destroy that target.' },
  { id: 't2', name: 'Mirror Force', type: 'trap', effect: 'destroy_attackers', description: 'When an opponent\'s monster declares an attack: Destroy all your opponent\'s Attack Position monsters.' },
  { id: 't3', name: 'Reinforcements', type: 'trap', effect: 'search_low_atk', description: 'Target 1 face-up monster on the field; it gains 500 ATK until the end of this turn.' },
  { id: 't4', name: 'Castle Walls', type: 'trap', effect: 'boost_atk_500', description: 'Increase the DEF of 1 face-up monster on the field by 500 points until the end of this turn.' },
  { id: 't5', name: 'Waboku', type: 'trap', effect: 'damage_prevention', description: 'You take no battle damage from your opponent\'s monsters this turn. Your monsters cannot be destroyed by battle this turn.' },
  { id: 't6', name: 'Two-Pronged Attack', type: 'trap', effect: 'destroy_both_500', description: 'Select and destroy 2 of your monsters and 1 of your opponent\'s monsters.' },
  { id: 't7', name: 'Reverse Trap', type: 'trap', effect: 'reflect_battle', description: 'Until the End Phase, all effects that add or subtract ATK or DEF are reversed. (Additions now subtract, and subtractions now add, instead. Multiplications and divisions, including halving/doubling, are not affected.)' },
  { id: 't8', name: 'Anti Raigeki', type: 'trap', effect: 'reflect_battle', description: 'When your opponent activates "Raigeki": Negate its effect, and if you do, destroy all monsters your opponent controls.' },
  { id: 't9', name: 'Dragon Capture Jar', type: 'trap', effect: 'flip_monsters_up', description: 'Change all face-up Dragon-Type monsters on the field to Defense Position, also they cannot change their battle positions.' },
  { id: 't10', name: 'Spellbinding Circle', type: 'trap', effect: 'lower_atk', description: 'Activate this card by targeting 1 monster your opponent controls; it cannot attack or change its battle position. When that monster is destroyed, destroy this card.' }
];

export { CARDS_PART4 };
