const CARDS_PART2 = [
  { id: 'm41', name: "Gaia the Fierce Knight", atk: 2300, def: 2100, type: 'monster', level: 7, attribute: 'earth', species: 'warrior', effect: null, description: "A knight who serves the earth spirit. Its shoulder pads are shaped like beasts." },
  { id: 'm42', name: "Curse of Dragon", atk: 2000, def: 1500, type: 'monster', level: 5, attribute: 'dark', species: 'dragon', effect: null, description: "An enchantress transformed into a dragon through dark magic." },
  { id: 'm43', name: "Mystic Tomato", atk: 1200, def: 800, type: 'monster', level: 4, attribute: 'dark', species: 'plant', effect: null, description: "A plant creature that destroys opponents with explosive seeds." },
  { id: 'm44', name: "Killer Spider", atk: 1100, def: 900, type: 'monster', level: 4, attribute: 'dark', species: 'insect', effect: null, description: "A large spider that traps prey in deadly webs." },
  { id: 'm45', name: "Fire Eyed Goblin", atk: 1000, def: 800, type: 'monster', level: 4, attribute: 'fire', species: 'goblin', effect: null, description: "A goblin with burning eyes that appear in flames." },
  { id: 'm46', name: "Soul Hunter", atk: 1300, def: 1100, type: 'monster', level: 4, attribute: 'dark', species: 'fiend', effect: null, description: "A hunter that stalks souls in the afterlife." },
  { id: 'm47', name: "Tainted Reality", atk: 900, def: 1000, type: 'monster', level: 4, attribute: 'dark', species: 'spellcaster', effect: null, description: "A mirror that reflects the darkest desires of the viewer." },
  { id: 'm48', name: "Electric Lizard", atk: 1000, def: 900, type: 'monster', level: 4, attribute: 'light', species: 'reptile', effect: null, description: "A lizard that discharges electricity from its tail." },
  { id: 'm49', name: "Stone D", atk: 800, def: 1200, type: 'monster', level: 4, attribute: 'earth', species: 'rock', effect: null, description: "A living statue that was once a statue guarding a temple." },
  { id: 'm50', name: "Pale Beast", atk: 1100, def: 800, type: 'monster', level: 4, attribute: 'dark', species: 'beast', effect: null, description: "A pale beast that roams the wastelands at night." },
  { id: 'm51', name: "Darkflare", atk: 1300, def: 900, type: 'monster', level: 5, attribute: 'dark', species: 'fiend', effect: null, description: "A fiend that burns everything with dark flames." },
  { id: 'm52', name: "B djinn", atk: 1200, def: 1000, type: 'monster', level: 5, attribute: 'dark', species: 'spellcaster', effect: null, description: "A djinn that serves darkness and grants cursed wishes." },
  { id: 'm53', name: "Witch of the Black Forest", atk: 1100, def: 800, type: 'monster', level: 4, attribute: 'dark', species: 'spellcaster', effect: null, description: "A witch that lives deep in the forest and casts hexes." },
  { id: 'm54', name: "Dark Titan", atk: 1400, def: 1200, type: 'monster', level: 5, attribute: 'dark', species: 'fiend', effect: null, description: "A massive titan that crushes enemies under its weight." },
  { id: 'm55', name: "Shadow Scout", atk: 800, def: 700, type: 'monster', level: 3, attribute: 'dark', species: 'fiend', effect: null, description: "A small shadow creature used for scouting." },
  { id: 'm56', name: "Roc from the Dark", atk: 1200, def: 1000, type: 'monster', level: 5, attribute: 'dark', species: 'winged beast', effect: null, description: "A dark bird of prey that hunts in the shadows." },
  { id: 'm57', name: "Turtle", atk: 700, def: 1200, type: 'monster', level: 3, attribute: 'water', species: 'reptile', effect: null, description: "A shell creature that retreats into its hard shell when attacked." },
  { id: 'm58', name: "Armored Star", atk: 900, def: 1100, type: 'monster', level: 4, attribute: 'earth', species: 'machine', effect: null, description: "A mechanical star that rolls over enemies." },
  { id: 'm59', name: "Hyo", atk: 1000, def: 900, type: 'monster', level: 4, attribute: 'water', species: 'aqua', effect: null, description: "A water spirit that appears during heavy rain." },
  { id: 'm60', name: "Dark Chimera", atk: 1400, def: 1000, type: 'monster', level: 5, attribute: 'dark', species: 'fiend', effect: null, description: "A chimera made of darkness that breathes dark fire." },
  { id: 'm61', name: "Mysterious Piranha", atk: 1100, def: 700, type: 'monster', level: 4, attribute: 'water', species: 'fish', effect: null, description: "A piranha with razor sharp teeth that hunts in schools." },
  { id: 'm62', name: "Skull Stalker", atk: 1200, def: 800, type: 'monster', level: 4, attribute: 'dark', species: 'zombie', effect: null, description: "A skeleton warrior that stalks the living." },
  { id: 'm63', name: "Saber Hunter", atk: 1300, def: 900, type: 'monster', level: 4, attribute: 'light', species: 'beast warrior', effect: null, description: "A hunter with a blade sharp enough to cut through armor." },
  { id: 'm64', name: "Kaminari Attack", atk: 1000, def: 800, type: 'monster', level: 4, attribute: 'light', species: 'thunder', effect: null, description: "A thunder spirit that strikes with lightning bolts." },
  { id: 'm65', name: "Bladefly", atk: 1100, def: 800, type: 'monster', level: 4, attribute: 'wind', species: 'winged beast', effect: null, description: "A flying insect with blade-like wings." },
  { id: 'm66', name: "Mech Bass", atk: 1200, def: 800, type: 'monster', level: 4, attribute: 'earth', species: 'machine', effect: null, description: "A mechanical bass that vibrates at deadly frequencies." },
  { id: 'm67', name: "Dark Blade", atk: 1300, def: 1000, type: 'monster', level: 5, attribute: 'dark', species: 'warrior', effect: null, description: "A cursed blade that thirsts for the blood of its enemies." },
  { id: 'm68', name: "Bonesato", atk: 900, def: 800, type: 'monster', level: 3, attribute: 'earth', species: 'skeleton', effect: null, description: "A skeleton that has been resurrected to serve." },
  { id: 'm69', name: "Sasuke", atk: 1000, def: 800, type: 'monster', level: 4, attribute: 'dark', species: 'warrior', effect: null, description: "A ninja that moves faster than the eye can see." },
  { id: 'm70', name: "Dark Puppeteer", atk: 800, def: 900, type: 'monster', level: 3, attribute: 'dark', species: 'spellcaster', effect: null, description: "A puppeteer who controls enemies with dark strings." },
  { id: 'm71', name: "Kagemusha", atk: 700, def: 900, type: 'monster', level: 4, attribute: 'dark', species: 'warrior', effect: null, description: "A shadow clone of a legendary samurai." },
  { id: 'm72', name: "D. Human", atk: 1100, def: 1000, type: 'monster', level: 4, attribute: 'dark', species: 'spellcaster', effect: null, description: "A human who has been transformed by dark magic." },
  { id: 'm73', name: "Grim Keeper", atk: 1200, def: 800, type: 'monster', level: 4, attribute: 'dark', species: 'fiend', effect: null, description: "A demon that guards the gates of the underworld." },
  { id: 'm74', name: "Moonlight", atk: 900, def: 800, type: 'monster', level: 3, attribute: 'light', species: 'spellcaster', effect: null, description: "A spirit that only appears under moonlight." },
  { id: 'm75', name: "Twilight", atk: 800, def: 900, type: 'monster', level: 3, attribute: 'dark', species: 'spellcaster', effect: null, description: "A shadow that exists between light and dark." },
  { id: 'm76', name: "Soul Keeper", atk: 1000, def: 1100, type: 'monster', level: 4, attribute: 'light', species: 'spellcaster', effect: null, description: "A guardian that protects lost souls from darkness." },
  { id: 'm77', name: "Night Sprite", atk: 800, def: 700, type: 'monster', level: 3, attribute: 'dark', species: 'fairy', effect: null, description: "A fairy that appears only at night to grant wishes." },
  { id: 'm78', name: "Golem Sentry", atk: 1100, def: 1300, type: 'monster', level: 5, attribute: 'earth', species: 'rock', effect: null, description: "A stone guardian that protects ancient temples." },
  { id: 'm79', name: "Dark Cat", atk: 900, def: 800, type: 'monster', level: 3, attribute: 'dark', species: 'beast', effect: null, description: "A black cat that brings misfortune to its enemies." },
  { id: 'm80', name: "Flame Ghost", atk: 1000, def: 800, type: 'monster', level: 4, attribute: 'fire', species: 'spirit', effect: null, description: "A ghost made of fire that haunts ancient ruins." }
];
export default CARDS_PART2;