const CARDS_PART3 = [
  // ===== MONSTER CARDS (m81-m100) =====
  { id: 'm81', name: "Dark Ruler Ha Des", atk: 2450, def: 1300, type: 'monster', level: 6, attribute: 'dark', species: 'fiend', effect: null, description: "Cannot be Normal Summoned/Set. Must be Special Summoned by a card effect. Cannot be destroyed by Spells or Traps while you control a Fiend monster." },
  { id: 'm82', name: "Mausoleum of the Emperor", type: 'spell', category: 'field', effect: 'field_spell', description: "You can pay 1000 LP to Normal Summon a monster without Tributing." },
  { id: 'm83', name: "Nights End", atk: 1000, def: 600, type: 'monster', level: 3, attribute: 'dark', species: 'spellcaster', effect: null, description: "When this card is destroyed by battle and sent to the GY, you can Special Summon 1 Level 4 or lower DARK monster from your hand." },
  { id: 'm84', name: "Soul Demolition", atk: 1300, def: 1000, type: 'monster', level: 4, attribute: 'dark', species: 'spellcaster', effect: null, description: "When this card destroys an opponent's monster by battle, you can excavate the top 3 cards of your Deck and return them to the deck in any order." },
  { id: 'm85', name: "Dark Grepher", atk: 1850, def: 800, type: 'monster', level: 4, attribute: 'dark', species: 'warrior', effect: null, description: "You cannot Special Summon monsters from the hand, Main Deck, or GY except DARK monsters. Once per turn, if you control no monsters, you can Normal Summon 1 DARK monster in addition to your Normal Summon." },
  { id: 'm86', name: "Armageddon Knight", atk: 1400, def: 1200, type: 'monster', level: 4, attribute: 'dark', species: 'warrior', effect: null, description: "When this card is Summoned, you can send 1 DARK monster from your Deck to the GY." },
  { id: 'm87', name: "Shadow Slayer", atk: 1600, def: 1200, type: 'monster', level: 5, attribute: 'dark', species: 'warrior', effect: null, description: "When this card battles a LIGHT monster, it gains 800 ATK during the Damage Step only." },
  { id: 'm88', name: "Morphing Jar", atk: 700, def: 600, type: 'monster', level: 2, attribute: 'earth', species: 'rock', effect: 'flip_morphing_jar', description: "FLIP: Discard your entire hand, then draw 5 cards." },
  { id: 'm89', name: "Sangan", atk: 1000, def: 600, type: 'monster', level: 3, attribute: 'dark', species: 'fiend', effect: 'search_1500_atk', description: "When this card is sent from the field to the Graveyard: Add 1 monster with 1500 or less ATK from your Deck to your hand." },
  { id: 'm90', name: "Kuriboh", atk: 300, def: 200, type: 'monster', level: 1, attribute: 'dark', species: 'fiend', effect: 'prevent_battle_damage', description: "During your opponent's turn, at damage calculation: You can discard this card; you take no battle damage from that battle (this is a Quick Effect)." },
  { id: 'm91', name: "Chrysanthemum", atk: 1000, def: 1000, type: 'monster', level: 3, attribute: 'earth', species: 'plant', effect: 'flip_draw_2', description: "FLIP: Draw 2 cards." },
  { id: 'm92', name: "D.D. Crow", atk: 1000, def: 800, type: 'monster', level: 3, attribute: 'dark', species: 'winged beast', effect: null, description: "During either player's Main Phase: You can banish 1 card from your opponent's hand. This effect cannot be used the turn this card is Summoned." },
  { id: 'm93', name: "Kahkki", atk: 800, def: 700, type: 'monster', level: 2, attribute: 'water', species: 'fish', effect: null, description: "When this card battles a WATER monster, it gains 500 ATK during the Damage Step only." },
  { id: 'm94', name: "Giant Rat", atk: 1200, def: 800, type: 'monster', level: 4, attribute: 'earth', species: 'beast', effect: null, description: "If this card is destroyed by battle: Special Summon 1 Level 4 or lower Beast monster from your hand." },
  { id: 'm95', name: "The Emperor's Priestess", atk: 1400, def: 1200, type: 'monster', level: 5, attribute: 'light', species: 'spellcaster', effect: null, description: "This card's name is treated as 'Breaker the Magical Warrior' on the field." },
  { id: 'm96', name: "Spirit of the Potter", atk: 900, def: 1100, type: 'monster', level: 4, attribute: 'earth', species: 'rock', effect: null, description: "Once per turn, you can reveal 1 card in your hand and equip it to this card. This effect changes its ATK to 1200." },
  { id: 'm97', name: "Guardian of the Throne Room", atk: 1500, def: 1700, type: 'monster', level: 6, attribute: 'light', species: 'spellcaster', effect: null, description: "You can pay 500 LP to add 1 Level 5 or higher Spellcaster monster from your Deck to your hand." },
  { id: 'm98', name: "Freed the Brave Wanderer", atk: 1600, def: 900, type: 'monster', level: 4, attribute: 'light', species: 'warrior', effect: null, description: "While you control 'The Trieagle', you can Normal Summon this card without Tributing." },
  { id: 'm99', name: "Marauding Captain", atk: 1200, def: 800, type: 'monster', level: 3, attribute: 'light', species: 'warrior', effect: null, description: "During your Main Phase, you can Normal Summon 1 Level 3 or lower Warrior monster in addition to your Normal Summon. You can only use this effect once per turn." },
  { id: 'm100', name: "D.D. Scout Plane", atk: 1400, def: 800, type: 'monster', level: 4, attribute: 'dark', species: 'machine', effect: null, description: "If this card is destroyed by a card effect and sent to the GY, draw 1 card." },

  // ===== EXODIA WIN CONDITION CARDS (m101-m105) =====
  { id: 'm101', name: "Exodia the Forbidden One", atk: 1000, def: 1000, type: 'monster', level: 3, attribute: 'dark', species: 'spellcaster', effect: 'exodia_piece', exodiaPiece: 'head', description: "If you have this card plus the Right Arm, Left Arm, Right Leg, and Left Leg of the Forbidden One in your hand, you win the Duel." },
  { id: 'm102', name: "Right Arm of the Forbidden One", atk: 200, def: 300, type: 'monster', level: 1, attribute: 'dark', species: 'spellcaster', effect: 'exodia_piece', exodiaPiece: 'right_arm', description: "One of the five Forbidden One cards required for an Exodia victory." },
  { id: 'm103', name: "Left Arm of the Forbidden One", atk: 200, def: 300, type: 'monster', level: 1, attribute: 'dark', species: 'spellcaster', effect: 'exodia_piece', exodiaPiece: 'left_arm', description: "One of the five Forbidden One cards required for an Exodia victory." },
  { id: 'm104', name: "Right Leg of the Forbidden One", atk: 200, def: 300, type: 'monster', level: 1, attribute: 'dark', species: 'spellcaster', effect: 'exodia_piece', exodiaPiece: 'right_leg', description: "One of the five Forbidden One cards required for an Exodia victory." },
  { id: 'm105', name: "Left Leg of the Forbidden One", atk: 200, def: 300, type: 'monster', level: 1, attribute: 'dark', species: 'spellcaster', effect: 'exodia_piece', exodiaPiece: 'left_leg', description: "One of the five Forbidden One cards required for an Exodia victory." },

  // ===== SPELL CARDS (s1-s15) =====
  { id: 's1', name: "Dark Hole", type: 'spell', category: 'normal', effect: 'destroy_all_monsters', description: "Destroy all monsters on the field." },
  { id: 's2', name: "Monster Reborn", type: 'spell', category: 'normal', effect: 'special_summon_grave', description: "Target 1 monster in either GY; Special Summon it." },
  { id: 's3', name: "Swords of Revealing Light", type: 'spell', category: 'normal', effect: 'flip_monsters_up', description: "Flip all face-down monsters on the field face-up. They cannot attack during this turn. This effect lasts for 3 turns after this card's activation." },
  { id: 's4', name: "Change of Heart", type: 'spell', category: 'quick-play', effect: 'take_control_opponent_monster', description: "Target 1 opponent's monster; take control of it until the End Phase." },
  { id: 's5', name: "The Hall of Dragon", type: 'spell', category: 'normal', effect: 'damage_1000', description: "Inflict 1000 damage to your opponent." },
  { id: 's6', name: "Dark Magic Veil", type: 'spell', category: 'normal', effect: 'destroy_opponent_backrow', description: "Pay 800 LP; destroy all Spell/Trap cards your opponent controls." },
  { id: 's7', name: "Mage Power", type: 'spell', category: 'equip', effect: 'boost_by_spells', description: "The equipped monster gains 500 ATK/DEF for each Spell/Trap card you control." },
  { id: 's8', name: "Premature Burial", type: 'spell', category: 'continuous', effect: 'special_summon_self_gy', description: "Pay 800 LP to Special Summon 1 monster from your GY. If this card is destroyed, destroy that monster." },
  { id: 's9', name: "Reload", type: 'spell', category: 'normal', effect: 'reload_hand', description: "Discard your entire hand, then draw the same number of cards you discarded." },
  { id: 's10', name: "Snatch Strike", type: 'spell', category: 'quick-play', effect: 'steal_opponent_card', description: "During the opponent's Main Phase: Target 1 face-up monster your opponent controls; take control of it until the End Phase." },
  { id: 's11', name: "Mind Control", type: 'spell', category: 'normal', effect: 'take_control_until_end', description: "Target 1 monster your opponent controls; take control of it until the End Phase." },
  { id: 's12', name: "Dark Magic Curtain", type: 'spell', category: 'ritual', effect: 'ritual_summon', description: "This card is used to Ritual Summon 'Dark Magician'. You must also send monsters from your hand or field to the GY whose total Levels equal 7." },
  { id: 's13', name: "Gold Sarcophagus", type: 'spell', category: 'normal', effect: 'banish_top_deck', description: "Banish the top card of your Deck face-down. After 2 turns, add that card to your hand." },
  { id: 's14', name: "Mesmeric Control", type: 'spell', category: 'normal', effect: 'drain_opponent_stat', description: "Target 1 face-up monster your opponent controls; its ATK becomes 0 until the end of the turn." },
  { id: 's15', name: "The Necklace of Fate", type: 'spell', category: 'continuous', effect: 'prevent_death_damage', description: "Once per turn, when you take battle damage, you can reduce that damage to 0." }
];
export default CARDS_PART3;