const CARDS_PART4 = [
  // ============================================
  // SPELL CARDS s16-s40
  // ============================================
  { id: 's16', name: "The Necklace", type: 'spell', category: 'continuous', effect: 'damage_prevention', description: '2+ monsters, including a Fiend monster\nDuring the Main Phase (Quick Effect): You can discard 1 card, then activate 1 of these effects;\n● Destroy 1 card on the field.\n● Banish this card (until the End Phase), and if you do, Special Summon 1 LIGHT or DARK monster from your GY.\nDuring your Standby Phase: You can draw cards equal to the number of different Monster Types in your GY, then place cards from your hand on the bottom of the Deck in any order, equal to the number of cards you drew. You can only use each effect of "A Bao A Qu, the Lightless Shadow" once per turn.' },
  { id: 's17', name: "Mysterious Sword", type: 'spell', category: 'equip', effect: 'atk_boost', description: 'During your Main Phase: You can reveal 1 Level 1 "Floowandereeze" monster in your hand and banish 1 "Floowandereeze" card with a different name from your Deck, then, immediately after this effect resolves, Normal Summon the revealed monster. If your opponent Normal Summons a monster: Immediately after this effect resolves, you can Normal Summon 1 "Floowandereeze" monster. You can only use each effect of "Floowandereeze and the Magnificent Map" once per turn.' },
  { id: 's18', name: "Malevolent Nuzzler", type: 'spell', category: 'equip', effect: 'atk_boost', description: 'When an opponent\'s monster declares an attack: Destroy all Spell and Trap Cards on the field.' },
  { id: 's19', name: "Spark of the Monkey King", type: 'spell', category: 'equip', effect: 'atk_boost', description: 'When this card is Normal Summoned: You can add 1 card that mentions "Black-Winged Dragon" from your Deck to your hand, except "Blackwing - Sudri the Phantom Glimmer". You can Tribute 1 monster; Special Summon 1 "Phantom Glimmer Token" (Winged Beast/Tuner/DARK/Level 2/ATK 700/DEF 700), then you take 700 damage. You cannot Special Summon monsters from the Extra Deck the turn you activate this effect, except Synchro Monsters. You can only use this effect of "Blackwing - Sudri the Phantom Glimmer" once per turn.' },
  { id: 's20', name: "Vile Quintet", type: 'spell', category: 'normal', effect: 'mill', description: 'A Plant-Type monster equipped with this card increases its ATK and DEF by 300 points.' },
  { id: 's21', name: "Dian Keto the Cure Master", type: 'spell', category: 'normal', effect: 'life_gain', description: '[ Pendulum Effect ] \nOnce per turn: You can Tribute 1 "Abyss Actor" monster, then target 1 "Abyss Actor" monster you control; it gains ATK equal to the original ATK of the Tributed monster, until the end of this turn (even if this card leaves the field).\n\n[ Monster Effect ] \nIf this card is Normal or Special Summoned: You can make this card gain 300 ATK for each "Abyss Actor" monster you currently control, until the end of this turn. You can target 1 other "Abyss Actor" monster you control; it gains ATK equal to this card\'s current ATK, until the end of this turn. This card cannot attack the turn this effect is activated. You can only use this effect of "Abyss Actor - Funky Comedian" once per turn.' },
  { id: 's22', name: "Dark Energy", type: 'spell', category: 'equip', effect: 'atk_boost', description: 'Increase the ATK and DEF of a Fiend-Type monster equipped with this card by 300 points.' },
  { id: 's23', name: "Ancient Telescope", type: 'spell', category: 'normal', effect: 'rearrange_top', description: 'If a card(s) is sent from the hand or Deck to your opponent\'s GY (except during the Damage Step): You can Special Summon this card from your hand, then you can Special Summon 1 Level 4 EARTH Fairy monster from your GY, except "Agido the Ancient Sentinel". If this card is sent from the hand or Deck to the GY: You can activate this effect; each player sends the top 5 cards of their Deck to the GY (or their entire Deck, if less than 5), then, if "Exchange of the Spirit" is in your GY, you can send 5 more cards from the top of either player\'s Deck to the GY. You can only use each effect of "Agido the Ancient Sentinel" once per turn.' },
  { id: 's24', name: "Book of Secret Arts", type: 'spell', category: 'equip', effect: 'spellcaster_boost', description: 'Change all face-up monsters on the field to face-down Defense Position. During the End Phase of this turn, change as many face-down Defense Position monsters your opponent controls as possible to face-up Defense Position, then your opponent draws cards equal to the number of monsters changed face-up by this effect.' },
  { id: 's25', name: "Dark Purple", type: 'spell', category: 'equip', effect: 'atk_boost', description: '(This card is always treated as an "Archfiend" card.)\nIf a Level 8 or higher monster under your control was sent to the Graveyard this turn: Special Summon 1 "Berserk Dragon" from your hand or Deck.' },
  { id: 's26', name: "The Injection Needle", type: 'spell', category: 'equip', effect: 'atk_boost', description: '2+ monsters, including a Fiend monster\nDuring the Main Phase (Quick Effect): You can discard 1 card, then activate 1 of these effects;\n● Destroy 1 card on the field.\n● Banish this card (until the End Phase), and if you do, Special Summon 1 LIGHT or DARK monster from your GY.\nDuring your Standby Phase: You can draw cards equal to the number of different Monster Types in your GY, then place cards from your hand on the bottom of the Deck in any order, equal to the number of cards you drew. You can only use each effect of "A Bao A Qu, the Lightless Shadow" once per turn.' },
  { id: 's27', name: "Rare Value", type: 'spell', category: 'normal', effect: 'exchange_hand', description: '"Fusionist" + "Enchanting Mermaid"'s hand with 1 random card from your own hand." },
  { id: 's28', name: "Enchanting Mists", type: 'spell', category: 'continuous', effect: 'damage_prevention', description: 'Pay 800 LP; excavate the top 4 cards of your Deck and Special Summon all excavated Level 3 or lower Normal Monsters, also, after that, shuffle the rest back into your Deck.' },
  { id: 's29', name: "Draining Shield", type: 'spell', category: 'continuous', effect: 'damage_prevention', description: 'When an opponent\'s monster declares an attack: Target the attacking monster; negate that attack, and if you do, gain LP equal to that target\'s ATK.' },
  { id: 's30', name: "Dark Eraser", type: 'spell', category: 'continuous', effect: 'damage_prevention', description: '(This card is always treated as an "Archfiend" card.)\nIf a Level 8 or higher monster under your control was sent to the Graveyard this turn: Special Summon 1 "Berserk Dragon" from your hand or Deck.' },
  { id: 's31', name: "Shadow of Void", type: 'spell', category: 'normal', effect: 'skip_draw', description: '2+ monsters, including a Fiend monster\nDuring the Main Phase (Quick Effect): You can discard 1 card, then activate 1 of these effects;\n● Destroy 1 card on the field.\n● Banish this card (until the End Phase), and if you do, Special Summon 1 LIGHT or DARK monster from your GY.\nDuring your Standby Phase: You can draw cards equal to the number of different Monster Types in your GY, then place cards from your hand on the bottom of the Deck in any order, equal to the number of cards you drew. You can only use each effect of "A Bao A Qu, the Lightless Shadow" once per turn.' },
  { id: 's32', name: "Crush Card", type: 'spell', category: 'normal', effect: 'draw', description: 'When this card battles a LIGHT monster, remove that monster from play after damage calculation.' },
  { id: 's33', name: "Metal Treasure", type: 'spell', category: 'normal', effect: 'life_gain', description: 'You can target 1 "Red-Eyes" monster you control; equip this monster from your hand or field to that target. It gains 600 ATK. If this card is sent from the field to the GY: You can add 1 "Red-Eyes" card from your Deck to your hand.' },
  { id: 's34', name: "Silver Pendant", type: 'spell', category: 'normal', effect: 'life_gain', description: '[ Pendulum Effect ] \n"Amazoness" monsters you control gain ATK equal to their own Level x 100. When an attack is declared involving your "Amazoness" monster: You can target 1 "Amazoness" Spell/Trap in your GY; add it to your hand. You can only use this effect of "Amazoness Silver Sword Master" once per turn.\n\n[ Monster Effect ] \nIf this card in the Monster Zone is destroyed by battle or card effect: You can place this card in your Pendulum Zone. If an "Amazoness" monster(s) is Special Summoned to your field, while this card is in your GY (except during the Damage Step): You can place this card in your Pendulum Zone. You can only use each effect of "Amazoness Silver Sword Master" once per turn.' },
  { id: 's35', name: "Dark Core", type: 'spell', category: 'normal', effect: 'destroy_monster', description: '(This card is always treated as an "Archfiend" card.)\nIf a Level 8 or higher monster under your control was sent to the Graveyard this turn: Special Summon 1 "Berserk Dragon" from your hand or Deck.' },
  { id: 's36', name: "Abyss Sea", type: 'spell', category: 'continuous', effect: 'field_spell', description: '[ Pendulum Effect ] \nYou can target 1 "Abyss Actor" Pendulum Monster you control and 1 monster your opponent controls; switch control of both monsters, then destroy this card. You can only use this effect of "Abyss Actor - Comic Relief" once per turn.\n\n[ Monster Effect ] \nYou take no battle damage from attacks involving this card. Once per turn, during your Standby Phase: Give control of this card to your opponent. Once per turn, if control of this face-up card changes: Activate this effect; the owner of this card can destroy 1 Set "Abyss Script" Spell in their Spell & Trap Zone.' },
  { id: 's37', name: "Flame Circle", type: 'spell', category: 'normal', effect: 'damage_redirect', description: 'While this card is equipped to a monster: You can add 1 Level 5 or lower FIRE Warrior monster from your Deck to your hand, then destroy this card. If this card is sent to the GY because the equipped monster is sent to the GY: You can target 1 Level 5 or lower FIRE Warrior monster in your GY; Special Summon it, also you cannot Special Summon monsters for the rest of the turn, except Warrior monsters. You can only use 1 ""Infernoble Arms - Durendal"" effect per turn, and only once that turn.' },
  { id: 's38', name: "Thunder Force", type: 'spell', category: 'equip', effect: 'atk_boost', description: 'This card cannot be Special Summoned. During the battle between an attacking "Ally of Justice" monster you control and a Defense Position monster whose DEF is lower than the ATK of the attacking monster, inflict the difference as Battle Damage to your opponent.' },
  { id: 's39', name: "Mystic Relay", type: 'spell', category: 'ritual', effect: 'ritual_summon', description: '● While in Attack Position: Attack Position Winged Beast, Insect, and Plant-Type monsters you control cannot be destroyed by battle.\n● While in Defense Position: Defense Position Winged Beast, Insect, and Plant-Type monsters you control cannot be targeted by, or be destroyed by, card effects.' },
  { id: 's40', name: "Spiral Gate", type: 'spell', category: 'quick-play', effect: 'bounce', description: 'During the turn in which your opponent has activated a monster effect in the hand or GY, you can activate this card from your hand. Target 1 monster your opponent controls; return it to the hand/Extra Deck, then if you have no Traps in your GY, your opponent can Special Summon 1 monster from their GY. If you activated this card from your hand, you cannot activate the effects of LIGHT or DARK monsters for the rest of this Duel. You can only activate 1 "Dominus Spiral" per turn.' },

  // ============================================
  // TRAP CARDS t1-t20
  // ============================================
  { id: 't1', name: "Trap Hole", type: 'trap', effect: 'destroy_monster', description: 'This effect can be used during either player\'s turn. When your opponent activates a Trap Card, Tribute this face-up card to negate the activation of the Trap Card and destroy it.' },
  { id: 't2', name: "Mirror Force", type: 'trap', effect: 'destroy_attackers', description: 'If a Level 7 monster(s) is Special Summoned to your field: Send 2 "Additional Mirror Level 7" from your hand and/or Deck to the GY, then target 1 of those monsters; Special Summon 2 monsters with the same name as that target from your Deck, then take damage equal to their combined original ATK, also, for the rest of this turn after this card resolves, you can only Special Summon from the Extra Deck once.'s monster declares an attack: Destroy all Attack Position monsters your opponent controls." },
  { id: 't3', name: "Ring of Destruction", type: 'trap', effect: 'destroy_both_damage', description: 'When this card is Pendulum Summoned: You can target 1 card on the field; return it to the hand. You can only use this effect of "Aether, the Empowering Dragon" once per turn.' },
  { id: 't4', name: "Wicked Dragon Wrath", type: 'trap', effect: 'destroy_monster', description: 'You can discard this card; add 1 "Lair of Darkness" from your Deck to your hand. You can Tribute 1 DARK monster; draw 1 card, or, if you Tributed a DARK monster other than this card to activate this effect, you can add 1 DARK monster with 2000 or more DEF from your Deck to your hand, instead. You can only use this effect of "Ahrima, the Wicked Warden" once per turn.'s monster on the field." },
  { id: 't5', name: "Nobleman of Crossout", type: 'trap', effect: 'flip_destroy', description: 'When this card you control is destroyed by battle with an opponent\'s attacking monster and sent to your Graveyard: You can Special Summon 1 "Gravekeeper\'s" monster from your Deck in face-down Defense Position, except "Gravekeeper\'s Nobleman".' },
  { id: 't6', name: "Reinforcement", type: 'trap', effect: 'search_low_atk', description: 'Target 1 Level 4 or lower Fiend monster in your GY; Special Summon it, then discard 1 Fiend monster. You can only activate 1 "Charge Into a Dark World" per turn.' },
  { id: 't7', name: "Dust Tornado", type: 'trap', effect: 'destroy_set_st', description: '1 Tuner + 1+ non-Tuner monsters\nIf this card is Synchro Summoned: You can Special Summon 1 Level 2 or lower Tuner from your GY. During the Main Phase (Quick Effect): You can Tribute this card; Special Summon 1 "Stardust Dragon" from your Extra Deck (this is treated as a Synchro Summon), then, immediately after this effect resolves, Synchro Summon 1 Synchro Monster using monsters you control as material. This turn, the monsters Synchro Summoned by this effect are unaffected by your opponent\'s activated effects. You can only use each effect of "Accel Synchro Stardust Dragon" once per turn.' },
  { id: 't8', name: "Shadow Spell", type: 'trap', effect: 'take_control', description: '2+ monsters, including a Fiend monster\nDuring the Main Phase (Quick Effect): You can discard 1 card, then activate 1 of these effects;\n● Destroy 1 card on the field.\n● Banish this card (until the End Phase), and if you do, Special Summon 1 LIGHT or DARK monster from your GY.\nDuring your Standby Phase: You can draw cards equal to the number of different Monster Types in your GY, then place cards from your hand on the bottom of the Deck in any order, equal to the number of cards you drew. You can only use each effect of "A Bao A Qu, the Lightless Shadow" once per turn.'s monster on the field. It cannot attack or change its battle position for 3 turns." },
  { id: 't9', name: "Decoy", type: 'trap', effect: 'swap_draw', description: '\'\'An angel of happiness that descends on the sacred mound. It\'s said that he lands along with his partner in order to perform a special ritual known as the Ceremonial First Pitch. After charming everyone with his elegant coat of fur and cute appearance, he finishes the ritual with a high-five.\n\nThe SHOTIME along with his partner will go on...\'\'' },
  { id: 't10', name: "Medal of the Caught", type: 'trap', effect: 'redirect_damage', description: 'When this Set card is destroyed and sent to the Graveyard by an opponent\'s card effect, shuffle this card into its owner\'s Deck. Then draw 1 card.'s monster: Redirect that damage to 1 opponent's monster instead." },
  { id: 't11', name: "Light of Redemption", type: 'trap', effect: 'life_gain', description: '2+ monsters, including a Fiend monster\nDuring the Main Phase (Quick Effect): You can discard 1 card, then activate 1 of these effects;\n● Destroy 1 card on the field.\n● Banish this card (until the End Phase), and if you do, Special Summon 1 LIGHT or DARK monster from your GY.\nDuring your Standby Phase: You can draw cards equal to the number of different Monster Types in your GY, then place cards from your hand on the bottom of the Deck in any order, equal to the number of cards you drew. You can only use each effect of "A Bao A Qu, the Lightless Shadow" once per turn.' },
  { id: 't12', name: "Curse of the Void", type: 'trap', effect: 'banish_top', description: 'Cannot be Normal Summoned/Set. Must be Special Summoned by a card effect. You can target 3 of your banished Fiend monsters; Special Summon this card from your hand, and if you do, shuffle those banished monsters into the Deck. During the End Phase, if this card is in the GY because it was destroyed in your Monster Zone by an opponent\'s card and sent there this turn: Special Summon this card from your GY, then, you can destroy cards your opponent controls, up to the number of face-up Spells/Traps you control with different names. You can only use each effect of "Curse Necrofear" once per turn.' },
  { id: 't13', name: "Counter Counter", type: 'trap', effect: 'negate_spell', description: 'Activate only while you control an "/Assault Mode" monster. Negate the activation of a Spell Card, Trap Card, or Effect Monster\'s effect and destroy it.' },
  { id: 't14', name: "Phantom Fog", type: 'trap', effect: 'lower_atk', description: '[ Pendulum Effect ] \nOnce per turn, at the end of the Damage Step, if your Dragon Pendulum Monster attacked an opponent\'s monster: You can activate this effect; it can attack again in a row. You cannot declare attacks the turn you activate this effect, except with that monster.\n\n[ Monster Effect ] \nCannot be Normal Summoned/Set. Must be Special Summoned (from your hand or face-up Extra Deck) by Tributing all monsters you control (min. 2), including a Dragon Pendulum Monster. You can only Special Summon "All-Eyes Phantom Dragon" once per turn this way. Once per turn, during damage calculation, if this card battles an opponent\'s monster: Double this card\'s current ATK until the end of this turn. Once per turn, when your opponent activates a Spell/Trap Card or effect (Quick Effect): You can send 1 Spell/Trap you control to the GY; negate the activation.' },
  { id: 't15', name: "Ancient Predicament", type: 'trap', effect: 'skip_draw_player', description: 'If a card(s) is sent from the hand or Deck to your opponent\'s GY (except during the Damage Step): You can Special Summon this card from your hand, then you can Special Summon 1 Level 4 EARTH Fairy monster from your GY, except "Agido the Ancient Sentinel". If this card is sent from the hand or Deck to the GY: You can activate this effect; each player sends the top 5 cards of their Deck to the GY (or their entire Deck, if less than 5), then, if "Exchange of the Spirit" is in your GY, you can send 5 more cards from the top of either player\'s Deck to the GY. You can only use each effect of "Agido the Ancient Sentinel" once per turn.' },
  { id: 't16', name: "Mirror Gate Strike", type: 'trap', effect: 'reflect_battle', description: 'If a Level 7 monster(s) is Special Summoned to your field: Send 2 "Additional Mirror Level 7" from your hand and/or Deck to the GY, then target 1 of those monsters; Special Summon 2 monsters with the same name as that target from your Deck, then take damage equal to their combined original ATK, also, for the rest of this turn after this card resolves, you can only Special Summon from the Extra Deck once.'s monster attacks: The attacking monster's ATK becomes 0 until the End Phase, then the opponent takes damage equal to the original ATK." },
  { id: 't17', name: "Thunder Claw", type: 'trap', effect: 'atk_boost_turn', description: 'This card cannot be Special Summoned. During the battle between an attacking "Ally of Justice" monster you control and a Defense Position monster whose DEF is lower than the ATK of the attacking monster, inflict the difference as Battle Damage to your opponent.' },
  { id: 't18', name: "Spirit Return", type: 'trap', effect: 'special_summon_grave', description: '(This card is always treated as a "Mermail" card.)\nYou can Tribute this card from your hand and 1 "Atlantean" or "Mermail" monster from your hand or field; take 1 Level 7 Fish, Sea Serpent, or Aqua monster from your Deck and either add it to your hand or Special Summon it, also you cannot Special Summon from the Extra Deck for the rest of this turn, except WATER monsters. During your opponent\'s turn (Quick Effect): You can banish this card from your GY and discard 1 card to the GY; draw 1 card. You can only use each effect of "Abyssrhine, the Atlantean Spirit" once per turn.' },
  { id: 't19', name: "Dark Ruler Masquerade", type: 'trap', effect: 'both_skip_draw', description: '(This card is always treated as an "Archfiend" card.)\nIf a Level 8 or higher monster under your control was sent to the Graveyard this turn: Special Summon 1 "Berserk Dragon" from your hand or Deck.' },
  { id: 't20', name: "Dragon's Fury", type: 'trap', effect: 'damage_double', description: 'Target 1 "Abyss Actor" monster you control; if it destroys your opponent\'s monster by battle this turn, your opponent banishes 3 monsters from their Extra Deck (their choice). If this Set card in its owner\'s control is destroyed by an opponent\'s card effect, and you have a face-up "Abyss Actor" Pendulum Monster in your Extra Deck: You can look at your opponent\'s Extra Deck, also banish 1 monster from their Extra Deck. You can only use this effect of "Abyss Script - Fire Dragon\'s Lair" once per turn.' }
];
export default CARDS_PART4;